# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Bagol Labs
email: bagollabs@gmail.com
author: Jay Paul Aying
description: > # "Write an awesome description for your new site here. 
  We cater your software and hardware needs.
copyright: 'Copyright &copy; 2015 Bagol Labs. All Rights Reserved.'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://facebook.com/bagollabs
  - title: twitter
    url: https://twitter.com/bagollabs
  #- title: github
  #  url: https://github.com/IronSummitMedia/startbootstrap
  #- title: linkedin
  #  url: 
